# Generated by Django 2.1.4 on 2018-12-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('way', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('week_day', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='way.Way')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
