version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    container_name: django
    build: .
    command: python /way_to_home/way_to_home/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/way_to_home
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis 

  redis:
    image: "redis"
    container_name: redis
    volumes:
      - ./redis:/var/lib/redis/data
    ports:
      - 6379

#  celery:
#    build: .
  #  entrypoint: ["celery", "worker", "-l", "info", "-A", "app.CELERY", "-Q", "general"]
#    environment:
#      C_FORCE_ROOT: "True"
#      DOCKER: 1
#    volumes:
#      - './way_to_home:/way_to_home'
#    depends_on:
#      - redis
