version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    restart: always
    container_name: django
    build: .
    command: bash -c "python ./way_to_home/manage.py migrate --noinput && python ./way_to_home/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/way_to_home
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  redis:
    image: "redis"
    container_name: redis
    volumes:
      - ./redis:/var/lib/redis/data
    ports:
      - 6379

  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/data
    ports:
      - 5672:5672

  celery:
    build: .
    container_name: celery_worker
    command: bash -c "cd way_to_home && celery -A way_to_home worker -l info"
    volumes:
      - .:/way_to_home
    depends_on:
      - postgres
      - redis
      - rabbitmq

  celery-beat:
    build: .
    container_name: celery_beat
    command: bash -c "cd way_to_home && celery -A way_to_home beat -l info"
    volumes:
      - .:/way_to_home
    depends_on:
      - celery

  demons:
    build: .
    container_name: demons
    command: bash -c "cd way_to_home/daemons && python gtfs_daemon.py 11 && python notifier_deamon.py"
    depends_on:
      - app
      - postgres
    volumes:
      - .:/way_to_home
